---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R 'business development' $DEPLOYPATH
    - /bin/cp -R 'countriesContent' $DEPLOYPATH
    - /bin/cp -R 'css' $DEPLOYPATH
    - /bin/cp -R 'fonts' $DEPLOYPATH
    - /bin/cp -R 'js' $DEPLOYPATH
    - /bin/cp -R 'mail' $DEPLOYPATH
    - /bin/cp -R 'staffing' $DEPLOYPATH
    
    
